# Generated by Django 2.2.2 on 2020-10-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='roomnumber',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
    ]
